medical/urls.py
from django.urls import path
from . import views


urlpatterns =[
         path('',views.medical, name='medical'),

]

new3/urls.py
from django.contrib import admin

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include('medical.urls')),
    path('accounts/',include('accounts.urls')),
    path('/task',include('tasks.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
#-*- coding:utf-8 -*-

from django.urls import path, re_path
from . import views

# namespace
app_name = 'tasks'

urlpatterns = [
    # Create a task
    path('create/', views.TaskCreateView.as_view(), name='task_create'),
    # Retrieve task list
    path('', views.TaskListView.as_view(), name='task_list'),
    # Retrieve single task object
    re_path(r'^(?P<pk>\d+)/$', views.TaskDetailView.as_view(), name='task_detail'),
    # Update a task
    re_path(r'^(?P<pk>\d+)/update/$', views.TaskUpdateView.as_view(), name='task_update'),
    # Delete a task
    re_path(r'^(?P<pk>\d+)/delete/$', views.TaskDeleteView.as_view(), name='task_delete')

    # # Create a task
    # path('create/', views.task_create, name='task_create'),
    # # Retrieve task list
    # path('', views.task_list, name='task_list'),
    # # Retrieve single task object
    # re_path(r'^(?P<pk>\d+)/$', views.task_detail, name='task_detail'),
    # # Update a task
    # re_path(r'^(?P<pk>\d+)/update/$', views.task_update, name='task_update'),
    # # Delete a task
    # re_path(r'^(?P<pk>\d+)/delete/$', views.task_delete, name='task_delete'),

]

'''In Class-based views, you have to call as_view() function so as to return a 
callable view that takes a request and returns a response. 
Its the main entry-point in request-response cycle in case of generic views.

as_view is the function(class method) which will connect my MyView class with its url.'''

medical/models.py
from django.db import models

# Create your models here.


class Doctors(models.Model):
    image = models.ImageField(upload_to='pics')
    name = models.CharField(max_length=100)
    specialist = models.CharField(max_length=100)
    experiance = models.IntegerField()
    email = models.EmailField()


class Patient(models.Model):
    image = models.ImageField(upload_to='pics')
    name = models.CharField(max_length=100)
    problem = models.CharField(max_length=100)
    email = models.EmailField()


# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'your-smtp-host'  # Your SMTP host
EMAIL_PORT = 587  # Your SMTP port number
EMAIL_USE_TLS = True  # Use TLS encryption
EMAIL_HOST_USER = 'gouse030203@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'your-email-password'  # Your email password
# DEFAULT_FROM_EMAIL = 'your-email@example.com'  # Your default "from" address

tasks/models.py
from django.db import models


# Create your models here.

class Status(models.TextChoices):
    UNSTARTED = 'u', "Not started yet"
    ONGOING = 'o', "Ongoing"
    FINISHED = 'f', "Finished"


class Task(models.Model):
    name = models.CharField(verbose_name="Task name", max_length=65, unique=True)
    status = models.CharField(verbose_name="Task status", max_length=1, choices=Status.choices)

    def __str__(self):
        return self.name

tasks/forms.py
#-*- coding:utf-8 -*-
from .models import Task
from django import forms

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = "__all__"

medical/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Doctors
# Create your views here.

def medical(request):
    doc = Doctors.objects.all()
    return render(request,'medical.html',{'doc':doc})

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from .models import Task
from .forms import TaskForm

# Create your views here.
# Functional based view
# Create a task
# def task_create(request):
#     if request.method == "POST":
#         form = TaskForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect(reverse("tasks:task_list"))
#     else:
#         form = TaskForm()
#
#     return render(request, "tasks/task_form.html", { "form": form, })
#
#
# # Retrieve task list
# def task_list(request):
#     tasks = Task.objects.all()
#     return render(request, "tasks/task_list.html", { "tasks": tasks,})
#
#
# # Retrieve a single task
# def task_detail(request, pk):
#     task = get_object_or_404(Task, pk=pk)
#     return render(request, "tasks/task_detail.html", { "task": task, })
#
#
# # Update a single task
# def task_update(request, pk):
#     task_obj = get_object_or_404(Task, pk=pk)
#     if request.method == 'POST':
#         form = TaskForm(instance=task_obj, data=request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect(reverse("tasks:task_detail", args=[pk,]))
#     else:
#         form = TaskForm(instance=task_obj)
#
#     return render(request, "tasks/task_form.html", { "form": form, "object": task_obj})
#
#
# # Delete a single task
# def task_delete(request, pk):
#     task_obj = get_object_or_404(Task, pk=pk)
#     task_obj.delete()
#     return redirect(reverse("tasks:task_list"))

# Class Based Views
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

class TaskListView(ListView):
    model = Task
    context_object_name = 'tasks'

class TaskDetailView(DetailView):
    model = Task

class TaskCreateView(CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('tasks:task_list')

class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('tasks:task_list')

class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy('tasks:task_list')

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Hi this is Gouse!!</h1>
</body>
</html>

templates/card.html
     {% extends 'medical.html' %}
     {% load static %}

  {% block title %}{% endblock %}
<!--    <script src="{% static 'js/card.js' %}"></script>-->
{% block content %}

   <div class="card-container">
       {% for doc in doc %}
  <div class="card">
    <div class="card-image">
      <img src="{{doc.image.url}}" alt="Image 1">
    </div>
    <div class="card-content">
      <h3 class="card-title">Title 1</h3>
      <div><button class="card-button"></button></div>
    </div>
  </div>
  {% endfor %}

  <!-- Repeat the above card divs to create more cards -->
</div>
     {% endblock %}

templates/contact.html
{% extends 'medical.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="static/contact.css">
</head>

{% block body %}
<div>
    <center>
 <h1>This is Contact Page</h1>
    <h4>For any issues related to Review Marks contact the Reviewing Faculty</h4>
        </center>
</div>

<div class="container contact">
  {% csrf_token %}
  <form action = "{% url 'contactus' %}" method="post">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-3">
      <div class="contact-info">
        <img src="https://image.ibb.co/kUASdV/contact-image.png" alt="image"/>
        <h2>Contact Us</h2>
        <h4>We would love to hear from you !</h4>
      </div>
    </div>
    <div class="col-md-9">
      <div class="contact-form">
        <div class="form-group">
          <label class="control-label col-sm-2" for="firstname">First Name:</label>
          <div class="col-sm-10">
          <input type="text" class="form-control" id="firstname" placeholder="Enter First Name" name="firstname">
          </div>
          <br>
          <br>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-2" for="lname">Last Name:</label>
          <div class="col-sm-10">
          <input type="text" class="form-control" id="lname" placeholder="Enter Last Name" name="lastname">
          </div>
        </div>
        <br>
        <br>
        <br>
        <div class="form-group">
          <label class="control-label col-sm-2" for="email">Email:</label>
          <div class="col-sm-10">
          <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
          </div>
        </div>
        <br>
          <br>
        <div class="form-group">
          <label class="control-label col-sm-2" for="comment">Comment:</label>
          <div class="col-sm-10">
          <textarea class="form-control" rows="8" id="comment" name="comment"></textarea>
          </div>
        </div>
        <br>
        <br>
        <br>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">Submit</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  </form>
</div>
{% endblock %}

</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
     <link rel="stylesheet" href="{% static 'home.css' %}">

</head>
<body>
      <h1 class="gmk">GOUSE MOHINUDDIN KHAN</h1>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
<form action="login" method="post">
     {% csrf_token %}
      <!-- Section: Design Block -->
<section class="text-center text-lg-start">
  <!-- Jumbotron -->
  <div class="container py-4">
    <div class="row g-0 align-items-center">
      <div class="col-lg-6 mb-5 mb-lg-0">
        <div class="card cascading-right" style="
            background: hsla(0, 0%, 100%, 0.55);
            backdrop-filter: blur(30px);
            ">
          <div class="card-body p-5 shadow-5 text-center">
            <h2 class="fw-bold mb-5">Login now</h2>
            <form>
              <!-- 2 column grid layout with text inputs for the first and last names -->

              <!-- Email input -->
              <div class="form-outline mb-4">
                <input type="text" id="form3Example3" class="form-control" name="username" />
                <label class="form-label" for="form3Example3">User Name</label>
              </div>

              <!-- Password input -->
              <div class="form-outline mb-4">
                <input type="password" id="form3Example4" class="form-control" name="password"/>
                <label class="form-label" for="form3Example4">Password</label>
              </div>

              <!-- Checkbox -->
              <div class="form-check d-flex justify-content-center mb-4">
                <input class="form-check-input me-2" type="checkbox" value="" id="form2Example33" checked />
                <label class="form-check-label" for="form2Example33">
                  Subscribe to our newsletter
                </label>
              </div>

              <!-- Submit button -->
              <button type="submit" class="btn btn-primary btn-block mb-4">
                Login
              </button>

              <!-- Register buttons -->
              <div class="text-center">
                <p>If you are not registered</p>
                <p>or sign up with: <a href="register">Sign up</a></p>
                <button type="button" class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-facebook-f"></i>
                </button>

                <button type="button" class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-google"></i>
                </button>

                <button type="button" class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-twitter"></i>
                </button>

                <button type="button" class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-github"></i>
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>

      <div class="col-lg-6 mb-5 mb-lg-0">
        <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" class="w-100 rounded-4 shadow-4"
          alt="" />
      </div>
    </div>
  </div>
  <!-- Jumbotron -->
</section>
<!-- Section: Design Block -->
  </form>
</body>

</html>

templates/medical.html
<!doctype html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="description" content="">
        <meta name="author" content="">

        <title>Supply Chain</title>

        <!-- CSS FILES -->        
        <link rel="preconnect" href="https://fonts.googleapis.com">
        
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&display=swap" rel="stylesheet">

        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <link href="{% static 'css/bootstrap-icons.css' %}" rel="stylesheet">

        <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">

        <link href="{% static 'css/owl.theme.default.min.css' %}" rel="stylesheet">

        <link href="{% static 'css/templatemo-medic-care.css' %}" rel="stylesheet">

        <link href="{% static 'css/card.css' %}" rel="stylesheet">
<!--

TemplateMo 566 Medic Care

https://templatemo.com/tm-566-medic-care

-->
    </head>
    
    <body id="top">
    
        <main>

            <nav class="navbar navbar-expand-lg bg-light fixed-top shadow-lg">
                <div class="container">
                    <a class="navbar-brand mx-auto d-lg-none" href="index.html">
                        Route Trace
                        <strong class="d-block">Route Trace</strong>
                    </a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav mx-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="#hero">Home</a>
                            </li>

                            <li class="nav-item">
                                {% if user.is_authenticated %}
                                <a class="nav-link" href="accounts/about">About</a>
                                {% elif user.is_anonymous %}
                                <a class="nav-link" href="#about">About</a>
                                {% endif %}
                            </li>

                            <li class="nav-item">
                                {% if user.is_authenticated %}
                                <a class="nav-link" href="accounts/contact">Contact</a>
                                {% elif user.is_anonymous %}
                                <a class="nav-link" href="#about">Contact</a>
                                {% endif %}
                            </li>


                            <a class="navbar-brand d-none d-lg-block" href="index.html">
                                 Route Trace
                                <strong class="d-block">Track Logistics</strong>
                            </a>

                            <li class="nav-item">
                                {% if user.is_anonymous %}
                                <a class="nav-link" href="accounts/register">Register</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="accounts/login">Login</a>
                            </li>

                            <li class="nav-item">
                                {% elif user.is_authenticated %}
                                <a class="nav-link" href="accounts/logout">Logout</a>
                                 {% endif %}
                            </li>
                        </ul>
                    </div>

                </div>
            </nav>

            <section class="hero" id="hero">
                <div class="container">
                    <div class="row">

                        <div class="col-12">
                            <div id="myCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel">
                                <div class="carousel-inner">
                                    <div class="carousel-item active">
                                        <img src="{% static 'images/slider/image3.jpg' %}" class="img-fluid" alt="">
                                    </div>

                                    <div class="carousel-item">
                                        <img src="{% static 'images/slider/image1.jpg' %}" class="img-fluid" alt="">
                                    </div>

                                    <div class="carousel-item">
                                        <img src="{% static 'images/slider/image2.jpg' %}" class="img-fluid" alt="">
                                    </div>
                                </div>
                            </div>

                            <div class="heroText d-flex flex-column justify-content-center">

                                <h1 class="mt-auto mb-2">
                                    Better
                                    <div class="animated-info">
                                        <span class="animated-item">Tracking</span>
                                        <span class="animated-item">Tracking</span>
                                        <span class="animated-item">Tracking</span>
                                    </div>
                                </h1>

                                <p class="mb-4">Route Trace is tracking websites allow you to track the status and location of your shipments in real-time, which is especially useful when you're waiting for a package or need to know when it will arrive.</p>

                                <div class="heroLinks d-flex flex-wrap align-items-center">
                                    <a class="custom-link me-4" href="#about" data-hover="Learn More">Learn More</a>

                                    <p class="contact-phone mb-0"><i class="bi-phone"></i> 010-020-0340</p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </section>

            <section class="section-padding" id="about">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-6 col-md-6 col-12">
                            <h2 class="mb-lg-3 mb-3">Route Trace API</h2>
                            <p>Take the first step by <a style="color:blue;" href="accounts/register">registering an account</a> with Route Trace</p>
                            <p> The Track API fetches tracking information based on your Platform Order Number or Easyship Shipment ID. The responses give the most recent status update for the shipment as well as a history of all checkpoints.</p>
                            <p>Register-->Login-->Select Courier Platform-->Enter Valid Order-ID-->Track Shipment</p>
                            <p>To add space below an HTML component, you can use CSS margin-bottom property. Here's an example code snippet:</p>
                        </div>

                        <div class="col-lg-4 col-md-5 col-12 mx-auto">
                            <div class="featured-circle bg-white shadow-lg d-flex justify-content-center align-items-center">
<!--                                <p class="featured-text"><span class="featured-number">12</span> Years<br> of Experiences</p>-->
                                    <img src="{% static 'images/gallery/circle.png' %}" class="img-fluid" alt="">
                            </div>
                        </div>

                    </div>
                </div>

            </section>

            <div class="container">
                 <h2 class="mb-lg-5 mb-5">Track your Courier</h2>
            <div class="card-container">
       {% for doc in doc %}
  <div class="card">
    <div class="card-image">
      <img src="{{doc.image.url}}" alt="Image 1">
    </div>
    <div class="card-content">
      <div class="button"><button class="card-button" >Track</button></div>
    </div>
  </div>
  {% endfor %}

  <!-- Repeat the above card divs to create more cards -->
</div>
                </div>


            {% block content %}{% endblock %}
<!--            <section class="gallery">-->
<!--                <div class="container">-->
<!--                    <div class="row">-->
<!--                        {% for doc in doc %}-->
<!--                        <div class="col-lg-6 col-6 ps-0">-->
<!--                            <img src="{{doc.image.url}}" class="img-fluid galleryImage" alt="get a vaccine" title="get a vaccine for yourself">-->
<!--                            Name       : {{doc.name}}<br>-->
<!--                            Specialist : {{doc.specialist}}<br>-->
<!--                            Experiance : {{doc.experiance}}<br>-->
<!--                            Gmail      : {{doc.email}}-->
<!--                        </div>-->
<!--                        {% endfor %}-->


<!--                    </div>-->
<!--                </div>-->
<!--            </section>-->


        </main>



        <!-- JAVASCRIPT FILES -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/scrollspy.min.js' %}"></script>
        <script src="{% static 'js/custom.js' %}"></script>
<!--

TemplateMo 566 Medic Care

https://templatemo.com/tm-566-medic-care

-->
    </body>
</html>

templates/register.html
<!DOCTYPE html>
<html>
<head>
     {% load static %}
     <style>
    .cascading-right {
      margin-right: -50px;
    }

    @media (max-width: 991.98px) {
      .cascading-right {
        margin-right: 0;
      }
    }
  </style>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Registeration</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
    <form action="register" method="post">
        {% csrf_token %}
        <!-- Section: Design Block -->
<section class="text-center text-lg-start">
  <!-- Jumbotron -->
  <div class="container py-4">
    <div class="row g-0 align-items-center">
      <div class="col-lg-6 mb-5 mb-lg-0">
        <div class="card cascading-right" style="
            background: hsla(0, 0%, 100%, 0.55);
            backdrop-filter: blur(30px);
            ">
          <div class="card-body p-5 shadow-5 text-center">
            <h2 class="fw-bold mb-5">Sign up now</h2>
            <form>
              <!-- 2 column grid layout with text inputs for the first and last names -->
              <div class="row">
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <input type="text" id="form3Example1" class="form-control" name="first_name" />
                    <label class="form-label" for="form3Example1">First name</label>
                  </div>
                </div>
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <input type="text" id="form3Example2" class="form-control" name="last_name" />
                    <label class="form-label" for="form3Example2">Last name</label>
                  </div>
                </div>
              </div>
              <div class="form-outline mb-4">
                <input type="text" id="form3Example" class="form-control" name="username" />
                <label class="form-label" for="form3Example4">UserName</label>
              </div>

              <!-- Email input -->
              <div class="form-outline mb-4">
                <input type="email" id="form3Example3" class="form-control" name="email" />
                <label class="form-label" for="form3Example3">Email address</label>
              </div>

              <!-- Password input -->
              <div class="form-outline mb-4">
                <input type="password" id="form3Example4" class="form-control" name="password1" />
                <label class="form-label" for="form3Example4">Password</label>
              </div>

              <div class="form-outline mb-4">
                <input type="password" id="form3Example5" class="form-control" name="password2" />
                <label class="form-label" for="form3Example4">Confirm Password</label>
              </div>

              <!-- Checkbox -->
              <div class="form-check d-flex justify-content-center mb-4">
                <input class="form-check-input me-2" type="checkbox" value="" id="form2Example33" checked />
                <label class="form-check-label" for="form2Example33">
                  Subscribe to our newsletter
                </label>
              </div>

              <!-- Submit button -->
              <button type="submit" class="btn btn-primary btn-block mb-4">
                Sign up
              </button>

              <!-- Register buttons -->
              <div class="text-center">
                <p>If you are already registered</p>
                <p>or Login with:<a href="login">Login</a></p>
                <button type="button" class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-facebook-f"></i>
                </button>

                <button type="button" class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-google"></i>
                </button>

                <button type="button" class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-twitter"></i>
                </button>

                <button type="button" class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-github"></i>
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>

      <div class="col-lg-6 mb-5 mb-lg-0">
        <img src="{% static 'images/gallery/login.jpg' %}" class="w-100 rounded-4 shadow-4"
          alt="" />
      </div>
    </div>
  </div>
  <!-- Jumbotron -->
</section>
<!-- Section: Design Block -->
    </form>

    <div>
        {% for message in messages %}
        <h3> {{message}}  </h3>
        {% endfor %}
    </div>

</body>
</html>

templates/task_confirm_delete.html
<!DOCTYPE html>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ task }}"?</p>
    <input type="submit" value="Confirm" />
</form>

templates/task_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task Detail</title>
</head>
<body>
<p> Task Name: {{ task.name }} | <a href="{% url 'tasks:task_update' task.id %}">Update</a> |
    <a href="{% url 'tasks:task_delete' task.id %}">Delete</a>
</p>
<p> Task Status: {{ task.get_status_display }} </p>
<p> <a href="{% url 'tasks:task_list' %}">View All Tasks</a> |
    <a href="{% url 'tasks:task_create'%}">New Task</a>
</p>
</body>
</html>

templates/task_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if object %}Edit Task {% else %} Create New Task {% endif %}</title>
</head>
<body>
<h3>{% if object %}Edit Task {% else %} Create New Task {% endif %}</h3>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" class="btn btn-success" value="Submit"></p>
    </form>
</body>
</html>

templates/task_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task List</title>
</head>
<body>
<h3>Task List</h3>
{% for task in tasks %}
    <p>{{ forloop.counter }}. {{ task.name }} - {{ task.get_status_display }}
        (<a href="{% url 'tasks:task_update' task.id %}">Update</a> |
        <a href="{% url 'tasks:task_delete' task.id %}">Delete</a>)
    </p>
{% endfor %}

<p> <a href="{% url 'tasks:task_create' %}"> + Add A New Task</a></p>
</body>
</html>

templates/track.html
<!DOCTYPE html>
<html>
  <head>
    <title>Order Status</title>
     <style>
      body {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
      }

      .content {
        text-align: center;
      }
    </style>
  </head>
  <body>
    <h1>Order Status</h1>
    <p>Enter your order ID:</p>
    <input type="text" id="order-id">
    <br>
    <button onclick="showStatus()">Check Status</button>
    <br><br>
    <p id="status-message"></p>

    <script>
      function showStatus() {
        const orderId = document.getElementById("order-id").value;
        const status = getOrderStatus(orderId);
        const statusMessage = `Order ${orderId} is ${status}.`;
        document.getElementById("status-message").innerHTML = statusMessage;
      }

      function getOrderStatus(orderId) {
        // This is where you would query a database or API to get the order status
        // For this example, we'll just return a random status
        const statuses = ["in progress", "shipped", "delivered"];
        const randomIndex = Math.floor(Math.random() * statuses.length);
        return statuses[randomIndex];
      }
    </script>
  </body>
</html>